# Algonius Wallet - golangci-lint configuration v1.59.1
# Minimal configuration for Go 1.23.10 compatibility

run:
  timeout: 5m
  tests: false
  go: "1.23.10"

issues:
  exclude-dirs:
    - tests
    - vendor
  exclude-files:
    - "_test\\.go$"
    - "test_.*\\.go$" 
    - "tests/.*\\.go$"
    - "mock_.*\\.go$"
    - ".*_mock\\.go$"

linters:
  disable-all: true
  enable:
    - errcheck       # Check for unchecked errors
    - unused         # Find unused code
    - ineffassign    # Detect ineffective assignments
    - misspell       # Fix spelling mistakes

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
  
  misspell:
    locale: US

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
