# Algonius Wallet - golangci-lint configuration v1.59.1
# Essential security and code quality checks only

version: 2

run:
  timeout: 5m
  tests: false
  go: "1.23.10"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - tests
    - tests/integration
    - tests/integration/env
    - vendor
    - .git
  exclude-files:
    - "**/*_test.go"
    - "**/test_*.go" 
    - "tests/**"
    - "tests/**/*.go"
    - "**/tests/**"
    - "**/*_mock.go"
    - "**/mock_*.go"
    - ".*_test\\.go$"
    - "tests/.*"
    - "tests/integration/.*"
    - "tests/integration/env/.*"
    - "**/go/pkg/mod/**"
    - "**/src/slices/**"
    - "**/src/os/**"
    - "**/src/net/**"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
        - ineffassign
        - govet
        - misspell
    - path: test_.*\.go
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
        - ineffassign
        - govet
        - misspell
    - path: tests/
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
        - ineffassign
        - govet
        - misspell
    - path: tests/integration/env/
      linters:
        - errcheck
        - gosec
        - staticcheck
        - unused
        - ineffassign
        - govet
        - misspell
    - path: ".*/(slices|os|net)/.*"
      linters:
        - typecheck
        - govet
        - staticcheck
    - text: "cannot range over seq"
      linters:
        - typecheck
    - text: "not enough arguments in call to time.Unix"
      linters:
        - typecheck
    - text: "o.String undefined"
      linters:
        - typecheck
    - text: "missing type in composite literal"
      linters:
        - typecheck

linters:
  enable:
    # Essential static analysis
    - govet          # Go vet built-in checks
    - staticcheck    # Comprehensive static analysis
    - errcheck       # Check for unchecked errors
    - unused         # Find unused code
    - ineffassign    # Detect ineffective assignments
    
    # Security (disabled due to false positives with integer conversions)
    # - gosec          # Security-focused checks
    
    # Code style (minimal)
    - misspell       # Fix spelling mistakes
    
    
  disable-all: true

linters-settings:
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  
  staticcheck:
    checks: ["all"]
  
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
  
  gosec:
    exclude:
      - G104  # Audit errors not checked (covered by errcheck)
      - G204  # Command execution (needed for CLI operations)
      - G304  # File path injection (false positives in tests)
      - G115  # Integer overflow conversion (safe in our use cases)
      - G301  # Directory permissions (acceptable for log/test directories)
      - G102  # Bind to all interfaces (needed for test environments)
  
  misspell:
    locale: US

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
