# Algonius Wallet - golangci-lint configuration v1.59.1
# Essential security and code quality checks only

version: 2

run:
  timeout: 5m
  tests: false
  go: "1.23.10"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - tests
    - vendor
  exclude-files:
    - "_test\\.go$"
    - "test_.*\\.go$" 
    - "tests/.*\\.go$"
    - "mock_.*\\.go$"
    - ".*_mock\\.go$"

linters:
  disable-all: true
  enable:
    # Essential static analysis
    - govet          # Go vet built-in checks
    - staticcheck    # Comprehensive static analysis
    - errcheck       # Check for unchecked errors
    - unused         # Find unused code
    - ineffassign    # Detect ineffective assignments
    
    # Code style (minimal)
    - misspell       # Fix spelling mistakes

linters-settings:
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - buildtag
      - copylocks
      - errorsas
      - httpresponse
      - loopclosure
      - lostcancel
      - nilfunc
      - printf
      - shift
      - stdmethods
      - structtag
      - tests
      - unmarshal
      - unreachable
      - unsafeptr
      - unusedresult
  
  staticcheck:
    checks: ["all"]
  
  errcheck:
    check-type-assertions: false
    check-blank: false
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
  
  misspell:
    locale: US

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true